using System;
using System.IO;

using MazesForProgrammers.DataStructures;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MazesForProgrammers.Tests.Masks
{
    [TestClass]
    public class TextMaskDisplayTests : OutputGridTest
    {
        [TestMethod]
        public void TextMask()
        {
            var maskText =
@"X........X
....XX....
...XXXX...
....XX....
X........X
X........X
....XX....
...XXXX...
....XX....
X........X";

            var file = $"mask_{DateTime.UtcNow.Ticks}.txt";
            File.WriteAllText(file, maskText);
            var mask = Mask.FromTextFile(file);

            Grid = new MaskedRectangleGrid(mask);
            Algorithm.ApplyTo(Grid);

            File.Delete(file);
        }

        [TestMethod]
        public void LongTextMask()
        {
            var maskText =
@"X........X
....XX....
...XXXX...
....XX....
X........X
X........X
....XX....
...XXXX...
....XX....
....XX....
...XXXX...
....XX....
X........X
X........X
....XX....
...XXXX...
....XX....
...XXXX...
....XX....
X........X
X........X
....XX....
...XXXX...
....XX....
....XX....
X........X";

            var file = $"mask_{DateTime.UtcNow.Ticks}.txt";
            File.WriteAllText(file, maskText);
            var mask = Mask.FromTextFile(file);

            Grid = new MaskedRectangleGrid(mask);
            Algorithm.ApplyTo(Grid);

            File.Delete(file);
        }
    }
}
